"""initial schema

Revision ID: 13b971e8e43f
Revises:
Create Date: 2026-06-22 14:57:41.722441

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13b971e8e43f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cpi_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("quarter", sa.Integer(), nullable=False),
        sa.Column("component", sa.String(), nullable=False),
        sa.Column("index_value", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("year", "quarter", "component"),
    )
    op.create_table(
        "quotes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("address_raw", sa.String(), nullable=True),
        sa.Column("district", sa.Integer(), nullable=True),
        sa.Column("quote_date", sa.Date(), nullable=True),
        sa.Column("total_labor_huf", sa.Integer(), nullable=False),
        sa.Column("total_material_huf", sa.Integer(), nullable=False),
        sa.Column("grand_total_huf", sa.Integer(), nullable=False),
        sa.Column("grand_total_adjusted_huf", sa.Integer(), nullable=True),
        sa.Column("inflation_target_date", sa.Date(), nullable=True),
        sa.Column("timeline_weeks_min", sa.Integer(), nullable=True),
        sa.Column("timeline_weeks_max", sa.Integer(), nullable=True),
        sa.Column("payment_schedule", sa.String(), nullable=True),
        sa.Column("has_slag_complication", sa.Boolean(), nullable=False),
        sa.Column("num_line_items", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("file_name"),
    )
    op.create_table(
        "work_categories",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("label_hu", sa.String(), nullable=False),
        sa.Column("label_en", sa.String(), nullable=False),
        sa.Column("cost_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "buyer_purchases",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("item_hu", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "general_notes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("note_hu", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "line_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("name_hu", sa.String(), nullable=False),
        sa.Column("category_key", sa.String(), nullable=True),
        sa.Column("labor_cost_huf", sa.Integer(), nullable=True),
        sa.Column("material_cost_huf", sa.Integer(), nullable=True),
        sa.Column("total_cost_huf", sa.Integer(), nullable=True),
        sa.Column("notes_hu", sa.String(), nullable=True),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("is_included", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_key"],
            ["work_categories.key"],
        ),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "not_included",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("item_hu", sa.String(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "quote_vectors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("quote_id", sa.Uuid(), nullable=False),
        sa.Column("chroma_chunk_id", sa.String(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["quote_id"],
            ["quotes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("quote_vectors")
    op.drop_table("not_included")
    op.drop_table("line_items")
    op.drop_table("general_notes")
    op.drop_table("buyer_purchases")
    op.drop_table("work_categories")
    op.drop_table("quotes")
    op.drop_table("cpi_records")
    # ### end Alembic commands ###
